### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by StarSheriff2** [StarSheriff2/expert-class#44]
Hello Code Reviewer,

- [x] [Link to GitHub Project here](https://github.com/StarSheriff2/expert-class/projects/1)

- [x] There are 4 people in this project:
 - [Breno Xavier](https://github.com/brenoxav/)
 - [Francis Uloko](https://github.com/francisuloko)
 - [Mihndim Julius](https://github.com/Mihndim2020)
 - [Arturo Alvarez](https://github.com/StarSheriff)
 - [x] Kanban board screenshot
![Screen Shot 2021-10-14 at 16 45 52](https://user-images.githubusercontent.com/61250665/137405588-7fc8d606-5b01-43ca-beae-5c29ae231d2e.png)

**Comment by SpaYco** [comment]
Hi @StarSheriff2 @brenoxav @francisuloko @Mihndim2020 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
